version: '3.1'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo
    networks:
      - frontend
      - backend
  vue-web:
    build:
      context: ../client/
      dockerfile: Dockerfile.prod
    networks:
      - frontend
    depends_on:
      - node-app
    ports:
      - 80:80
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - mongodata:/data/db
      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongodata:

networks:
  frontend:
  backend: